# Generated by Django 4.2.6 on 2023-10-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rabis_hepatitis_past_1_year', models.BooleanField(null=True)),
                ('tatoo_surgery_past_6_months', models.BooleanField(null=True)),
                ('donated_blood_past_3_months', models.BooleanField(null=True)),
                ('immunisation_past_1_month', models.BooleanField(null=True)),
                ('anitibiotics_past_48_hrs', models.BooleanField(null=True)),
                ('alcoholic_bevarage_past_24_hrs', models.BooleanField(null=True)),
                ('asprin_dentalwork_past_72_hrs', models.BooleanField(null=True)),
                ('cough_common_presently', models.BooleanField(null=True)),
                ('pregnant_breastFeeding_presently', models.BooleanField(null=True)),
                ('menstration_presently', models.BooleanField(null=True)),
                ('health_check_1', models.BooleanField(null=True)),
                ('health_check_2', models.BooleanField(null=True)),
                ('age_betwn_18_60', models.BooleanField(null=True)),
                ('body_weight_less_45', models.BooleanField(null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_needed', models.DateField(null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
            ],
        ),
    ]
